### PR TITLE
Issues/478

### LINKED ISSUE #478: Make sure user entered text for event type: other is submitted by new event and edit forms
type: other: balbalbal

### PR DESCRIPTION
**Pull request by qclin**
fixes #478

### CODE REVIEW

**Comment by matthewberryman** [comment]
Note I checked in prod database and there are 4 events that have metadata.region specified that I can manually re-enter, i.e. safe for you to ignore that field but you do need to handle missing .areas properly.

**Comment by qclin** [comment]
@matthewberryman migrated inline editing code for handling types & other fields to modal view
please review

**Comment by matthewberryman** [comment]
Not always working. I will send you a DB dump  separately—note the ID number in the video for testing & so you can check the corresponding data in the database, although I'm seeing this on a number of events already in the system.
https://www.dropbox.com/s/qulwrttd2rfbzzz/other_types_issue.mp4?dl=0

**Comment by qclin** [comment]
@matthewberryman you're right, 
for the older entries that never entered an others type
it is fixed now

**Pull request merged**
