### PR TITLE
Visa multiple country

### PR DESCRIPTION
**Pull request by mehrdadgit**

### CODE REVIEW

**Comment by matthewberryman** [comment]
Thanks @mehrdadgit . The "required" option needs to be per nationality. Or if that's too hard I guess we can make the the list simply of nationalities that require a visa (thus no need for a "required" yes/no as it's implicit in the fact a nationality is listed). Thoughts @anexact @LucieGueuning ?

Also, we need somewhere in the "extra details" of event details to display this.

**Comment by mehrdadgit** [comment]
> Thanks @mehrdadgit . The "required" option needs to be per nationality. Or if that's too hard...
No too hard @matthewberryman I will fix that soon...

**Comment by mehrdadgit** [comment]
"required" per nationality done @matthewberryman

**Comment by matthewberryman** [comment]
@mehrdadgit still needs display under extra details section as requested

**Comment by mehrdadgit** [comment]
Done @matthewberryman

**Comment by mehrdadgit** [comment]
I am merging this @matthewberryman to avoid conflicts, if you wanted to do modification/wording change please do it on dev...

**Comment by matthewberryman** [comment]
Event edit modal has broken elements e.g. slider and won't submit as there's no handling of the case where the nationality metadata property isn't set. Since you've already merged this (please in future resolve the conflicts and then wait for review) can you please urgently fix in dev @mehrdadgit 

screenshot 2018-03-04 18 04 15
screenshot 2018-03-04 18 04 15

**Comment by mehrdadgit** [comment]
@matthewberryman This did not show up on my local machine but I noticed that on dev; it's because of the old JSON structure of the current metadata in DB (change from object to array) attempted a fix in https://github.com/MSFREACH/msf-reach/commit/ff9f58752eeefef5a56e8e691f699f0d6f7efd0a 
This tricky as it occurs with data on dev... let me have another go, if not fixed I will ask you to send me db dump of dev ( or configuring my local server to point to dev server if possible/easier  )

**Comment by mehrdadgit** [comment]
Done @matthewberryman as well as a typo fix. Seems ok now.

**Pull request merged**
