### PR TITLE
fixes #79

### LINKED ISSUE #79: support different roles
https://github.com/usergroupcoop/msf-reach/issues/75

### PR DESCRIPTION
**Pull request by stefan-devika**

### CODE REVIEW

**Comment by matthewberryman** [comment]
@stefan-devika I'm getting a redirection loop:
```
➜ curl -I https://test.msf-reach.org/
HTTP/1.1 302 Found
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
Cache-control: no-cache="set-cookie"
Content-Length: 28
Content-Type: text/plain; charset=utf-8
Date: Mon, 26 Mar 2018 22:10:37 GMT
Expires: 0
Location: /login
Pragma: no-cache
Server: nginx/1.12.1
Set-Cookie: AWSELB=BD137739106D7BA57BA7558E0A0515D6AD34C03C7D89446EA8969F1422EFB5AAAAAF49642BBE78AED4C96A46BF20B89E11B794C01F5F945099ED83B0AA72FAAD87BDF91AA2;PATH=/;MAX-AGE=3600
Surrogate-Control: no-store
Vary: Accept
X-Powered-By: Express
Connection: keep-alive


~
➜ curl -I https://test.msf-reach.org/login
HTTP/1.1 302 Found
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
Cache-control: no-cache="set-cookie"
Content-Length: 28
Content-Type: text/plain; charset=utf-8
Date: Mon, 26 Mar 2018 22:10:44 GMT
Expires: 0
Location: /login
Pragma: no-cache
Server: nginx/1.12.1
Set-Cookie: AWSELB=BD137739106D7BA57BA7558E0A0515D6AD34C03C7D89446EA8969F1422EFB5AAAAAF49642BBE78AED4C96A46BF20B89E11B794C01F5F945099ED83B0AA72FAAD87BDF91AA2;PATH=/;MAX-AGE=3600
Surrogate-Control: no-store
Vary: Accept
X-Powered-By: Express
Connection: keep-alive
```

**Comment by stefan-devika** [comment]
Hey, the continuous integration has stopped. It has not built my last
couple of commits from the past hour. I sent a commit to try and wake it up
but it still won't update, so my progress is at halt for now.

On Wed, Mar 28, 2018 at 10:50 AM, Matthew Berryman <notifications@github.com

**Comment by matthewberryman** [comment]
https://github.com/MSFREACH/msf-reach/issues/350

**Comment by matthewberryman** [comment]
@stefan-devika the build failures caused by an invalid docker image (see #350 and https://github.com/nodejs/docker-node/issues/675 ) are now resolved by swapping to a working copy of the node image I have.
You separately have a syntax error that's stopping the build (and hence deployment):
```
SyntaxError: src/lib/util.js: Unexpected token (58:78)
56 | */
57 | 
> 58 | if (req.user.groups.indexOf(config.AZURE_AD_OPERATORS_GROUP_ID) > -1) && req.isAuthenticated()) { //since express-jwt is "Middleware that validates JsonWebTokens and sets req.user." this should work.
| ^
59 | return next();
60 | }
61 | res.redirect('/login');
```

**Comment by stefan-devika** [comment]
Sorry, I should of caught that. Pushing to resolve now.

**Comment by matthewberryman** [comment]
@stefan-devika closing this pull request, open a new one with "fixes #79" so I can track when you're ready for me to review. Please be sure to resolve any merge conflicts first and also run `eslint --fix .` to check for any linter-spotted issues as well.

**Comment by stefan-devika** [comment]
Password for the test operator has expired and has been changed. The new
login is:

Operator login:
Username: reach.test@msfintltest.org
P/w: Mp86uktOW8401

**Pull request closed without merging**
