### PR TITLE
New event modal

### PR DESCRIPTION
**Pull request by matthewberryman**
@mehrdadgit refer to git commit 7c98f8efd03f1408d56ddf5ee16cab99fc4e2baa comments and generally review

### CODE REVIEW

**Comment by mehrdadgit** [comment]
I updated my local db for the other PR schema changes and now this branch is not working; shall we merge the latest changes into this one first?

**Comment by matthewberryman** [comment]
I will merge in a second

**Comment by matthewberryman** [comment]
@mehrdadgit I double checked and this branch is already up-to-date with the other changes 
PS when reviewing can you click on the button to approve rather than commenting, when approved.

**Comment by mehrdadgit** [comment]
It was not loading events on the landig page for me .. going home now will double check tonight ..

**Comment by matthewberryman** [comment]
Wait no it's not got latest changes, I'd forgotten to git pull the upstream merge (doh). Will work on this now. Spotted one other bug in event edit modal too.

**Comment by matthewberryman** [comment]
Travis-CI broke just because there's no corresponding branch in msf-reach-schema (I will need to fix up the .travis.yml to handle that case); safe to ignore this.

**Pull request merged**
