### PR TITLE
fixes #579 updateSection

### LINKED ISSUE #579: edit save consistency
Like for the event general information section, have a save button at the top of each in-line editing section, so the user doesn't need to do a cumbersome two step process of clicking done then scrolling down to press save button.

### PR DESCRIPTION
**Pull request by qclin**
fixes #579

### CODE REVIEW

**Comment by matthewberryman** [comment]
* Region: skip this as we now have this well covered by your work on areas- thanks!
* The rest: have a look at the modal edit fields and be consistent with the existing work there.

**Comment by matthewberryman** [comment]
@qclin I'm happy with your work on (1) in cd0c3b0 but still awaiting completion of (2) correct behaviour on cancellation.

**Comment by qclin** [comment]
@matthewberryman 
as I said reseting data to temp copy means atm some form of Jquery swapping on innerText/Value of every field
most ideal would be to do a hard refresh per section, but right now it's all one long html 

in https://github.com/MSFREACH/msf-reach/pull/590/commits/5bc63ae480bf475b7d223a9f6e693531c1747e3a I tried to clear the fields manually and let VUE model repopulate
however this only works on the first `cancel`

**Comment by mehrdadgit** [comment]
@qclin @matthewberryman 
Note I tested https://github.com/MSFREACH/msf-reach/commit/5bc63ae480bf475b7d223a9f6e693531c1747e3a  (in 537) does not work and is not a good practice anyway.
@qclin If (2) is too much work, I suggest you do a page-refresh on cancel ( requires enforcing only one section is being edited at a time ) and then we can create a new issue for (2) @matthewberryman ?

**Comment by matthewberryman** [comment]
Thanks @mehrdadgit. @qclin can you please add a commit that wraps up (2) with a page cancel for now and I can re-open a new issue as suggested for a more elegant-looking fix.

Sent from my iPhone

On 26 Aug 2018, at 23:52, Mehrdad <notifications@github.com<mailto:notifications@github.com>> wrote:


@qclin<https://github.com/qclin> @matthewberryman<https://github.com/matthewberryman>
Note I tested 5bc63ae<https://github.com/MSFREACH/msf-reach/commit/5bc63ae480bf475b7d223a9f6e693531c1747e3a> (in 537) does not work and is not a good practice anyway.
@qclin<https://github.com/qclin> If (2) is too much work, I suggest you do a page-refresh on cancel ( requires enforcing only one section is being edited at a time ) and then we can create a new issue for (2) @matthewberryman<https://github.com/matthewberryman> ?

**Comment by qclin** [comment]
@matthewberryman  done, please merge and create new ticket for STORE function
@mehrdadgit  this will override the work you've done on stopEdits 
also on good practice, clearing the field and letting VUE repopulate is essentially what a hard refresh do

**Comment by mehrdadgit** [comment]
I did some ui polishes and also forced the user to edit one section at a time, otherwise the user clicks on Edit for two sections -> cancels on one -> refresh -> losing all the edited data in the other one.
@matthewberryman ready to merge

**Comment by matthewberryman** [comment]
I've approved this and will merge into dev as I can't afford to hold up #612 however these changes break the display and saving of the severity sliders that will need to be fixed after I merge. I'll merge some other changes from dev -> master first before this merge, to not hold those up either.

**Pull request merged**
